---
- hosts: myBastion
  become: true
  tasks:

    - name: "rhel9-unit-virtualization : yum install packages"
      yum: name=qemu-kvm,libvirt,firewalld,virt-install,libvirt-client,libguestfs-tools,wget,cockpit-machines state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5

    - name: "rhel9-unit-virtualization : service restart libvirtd"
      service: name="libvirtd" state=started enabled=yes

    - name: "rhel9-unit-virtualization : firewalld service start"
      service: name="firewalld" state=started enabled=yes

    - name: "rhel9-unit-virtualization : workshop script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2',           dest: '/usr/local/bin/workshop-virt-checkhost.sh'}

    - name: "rhel9-unit-virtualization : workshop file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2', dest: '/usr/local/bin/workshop-virt-checkhost.sh'}

