---
- hosts: myBastion
  become: true
  tasks:
  
    - name: "rhel9-unit-wayland : yum install packages"
      yum: name=gnome-tweaks state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5
      
    - name: "rhel9-unit-wayland : user modification"
      user: name="{{ workshop_vars.student_name }}" groups="wheel"
            
    - name: "rhel9-unit-wayland : workshop file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'workshop-checkhost.j2', dest: '/usr/local/bin/workshop-wayland-checkhost.sh'} 
